### ISSUE TITLE
Visualization of the regression plot of vector points in your paper

### ISSUE THREAD

**Issue by HyeonnSeo** [lynn-yu/DTCLMapper#2]
Hello. Thank your for your great research.
I want to visualize the regression plot in your paper Fig 2 for analysis.
Is there any tools or codes for this?

Thank you.

**Comment by lynn-yu** [comment]
Thanks for your attention. We put this code on lines 382-399 in tools/maptrv2/av2_vis_pred.py. Note that this code only works if the forward_test module outputs the regression points.
